# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  swoop:
    cmds:
      - qmk compile -kb bluebell/swoop -km miryoku -e CONVERT_TO=promicro_rp2040
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
